About section
nwplus/external-templates pull request #308
Opened 2023-02-03 09:58 UTC by DonaldKLee

![image](https://user-images.githubusercontent.com/51865552/216570452-a42afaf0-0941-4aca-a508-80fc9b7b9d66.png)
![image](https://user-images.githubusercontent.com/51865552/216570569-bdefe022-1c74-4156-acaf-1bcc6cfe8731.png)

2023-02-07 18:14 UTC, naijwu requested changes

2023-02-07 18:14 UTC, naijwu commented on src/sections/About.jsx
>    <AboutContainer>
Text position looks slightly off (I'm viewing in a MBP viewport)

<img width="779" alt="image" src="https://user-images.githubusercontent.com/26179641/217330136-fc3b9c4a-81b3-4285-96c8-984f90a4d621.png">

2023-02-07 18:14 UTC, naijwu commented on src/sections/About.jsx
> +const swingSign = keyframes`
The animation looks wrong for me (goes up and down). Looks as if the origin point of the transformation is center left. 

May need to tweak the `transform-origin` attribute in the CSS as well

2023-02-11 07:54 UTC, DonaldKLee commented
![image](https://user-images.githubusercontent.com/51865552/218247177-7a90d7f9-c652-4e2c-8560-e17829871758.png)
![image](https://user-images.githubusercontent.com/51865552/218247184-6acd0ff8-0b5a-4646-8562-7a2943c0e99e.png)

2023-02-11 21:26 UTC, merged